### ISSUE TITLE
Invalid configuration when upgrading to v6.0.0

### ISSUE THREAD

**Issue by qaiserali** [Azure/terraform-azurerm-caf-enterprise-scale#1024]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 3.107

**azure provider**: 3.111.0

**module**: 6.0.0

**azapi**: 1.13.1

#### Describe the bug

I encountered the following error while upgrading the CAF module from version v5.2.0 to v6.0.0. I have followed the upgrade guide available at https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BUser-Guide%5D-Upgrade-from-v5.2.1-to-v6.0.0  and made the necessary modifications.

```
Error: Invalid configuration
│ 
│   with module.alz.azapi_resource.diag_settings["/providers/Microsoft.Management/managementGroups/mg-tele2-platform"],
│   on .terraform/modules/alz/resources.management_groups.tf line 81, in resource "azapi_resource" "diag_settings":
│   81: resource "azapi_resource" "diag_settings" {
│ 
│ embedded schema validation failed: the argument "body" is invalid:
│ `location` is not expected here. Do you mean `id`? 
│  You can try to update `azapi` provider to the latest version or disable the validation using the feature flag `schema_validation_enabled = false` within the resource block

```

As mentioned above, the azureapi provider version has been updated to 1.13.1.

Additionally, upon reviewing the resource definition at https://learn.microsoft.com/en-us/azure/templates/microsoft.insights/2021-05-01-preview/diagnosticsettings?pivots=deployment-language-terraform, it appears that the API does not support a property named 'location'.

**Comment by qaiserali** [comment]
@matt-FFFFFF  Any updates when are you going to merge this with v6.0.0? I can see the fix has been merged to the main branch.

**Comment by matt-FFFFFF** [comment]
fixed by #1053

**Comment by qaiserali** [comment]
@matt-FFFFFF The issue remains unresolved in v6.0.0. The fix needs to be merged into v6.0.0.

**Comment by matt-FFFFFF** [comment]
It will be included in 6.1

**Comment by qaiserali** [comment]
@matt-FFFFFF great, when are you planning to release 6.1?
